    printf("       __  __                    \n");
    printf("   /\\ |__)|__)                   \n");
    printf("  /--\\| \\ |                      \n");
    printf("                                 \n");
    printf("   __      __ __ __ __           \n");
    printf("  (_ ||\\ ||_ |_ |_ |__)          \n");
    printf("  __)|| \\||  |  |__| \\           \n");
    printf("                                 \n");
    printf("   __  _____ __ _____  __        \n");
    printf("  |  \\|_  | |_ /   | |/  \\|\\ |   \n");
    printf("  |__/|__ | |__\\__ | |\\__/| \\|   \n");
    printf("                                 \n");
    printf("  ___ __  __            __       \n");
    printf("   | /  \\/  \\|    \\  / /  \\    /|\n");
    printf("   | \\__/\\__/|__   \\/  \\__/.    |\n");
    printf("                                 \n");
    printf("                                 \n");                                                          
    printf("ARP sniffer spoof Detector tool v0.1\n");
    return 0;